services:
  yamq:
    image: rabbitmq:management-alpine
    container_name: ${CONTAINER_NAME}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASS}
    networks:
      - bee-network            
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
    networks:
      - bee-network            
    ports:
      - "${DB_PORT}:${DB_PORT}" 
    volumes:
      - ./innitDB.sql:/docker-entrypoint-initdb.d/init.sql      

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vagner@visualsoftware.inf.br"
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    networks:
      - bee-network            
    ports:
      - "16543:80"
    depends_on:
      - db

  web1:
    container_name: bee_app_1
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - bee-network      
    ports:
      - 3000:3000

  # web2:
  #   container_name: bee_app_2
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - bee-network      
  #   expose:
  #     - 3000

  # web3:
  #   container_name: bee_app_3
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - bee-network      
  #   expose:
  #     - 3000

  # web4:
  #   container_name: bee_app_4
  #   build:
  #     context: .
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - bee-network      
  #   expose:
  #     - 3000            

  # nginx:
  #   container_name: bee_balancer
  #   image: nginx:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - web1
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - bee-network
  #   ports:
  #     - 80:80

networks:
  bee-network:
    driver: bridge      